FROM physikerwelt/mediawiki
RUN apt-get update && \
    apt-get install -y --no-install-recommends git zip
RUN docker-php-ext-install zip
COPY --from=composer:1.9.1 /usr/bin/composer /usr/local/bin/composer
RUN ["composer","install"]

ENTRYPOINT ["docker-php-entrypoint", "apache2-foreground"]
