version: '3.4'
services:
  mediawiki:
    container_name: mw
    build: .
    restart: always
    ports:
      - 8080:80
    links:
      - database
    volumes:
      - mw-images:/var/www/html/images
  database:
    container_name: db
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
    volumes: 
      - mw-database:/var/lib/mysql
      - ./dumps:/docker-entrypoint-initdb.d
    secrets:
      - db_root_password
secrets:
   db_root_password:
     file: secret/db_root_password.txt
volumes:
  mw-images:
  mw-database: