version: '3.4'
services:
  mediawiki:
    container_name: mw
    build: .
    image: physikerwelt/mediawiki
    restart: always
    ports:
      - "80:80"
    links:
      - database
  database:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
    volumes: 
      - mw-database:/var/lib/mysql
      - ./dumps:/docker-entrypoint-initdb.d
    secrets:
      - db_root_password
    labels:
      - "traefik.enable=false"
secrets:
   db_root_password:
     file: secret/db_root_password.txt
volumes:
  mw-database: