#!/bin/sh
set -eu
# from https://github.com/addshore/mediawiki-docker-dev/blob/master/hosts-add
# Keep note of host names, so that users can use
# ./hosts-sync to test their current state and
# attempt to save it manually.
echo "127.0.0.1 $1 # mediawiki-docker-dev" >> .hosts